package com.hartwig.actin.datamodel.clinical

import com.hartwig.actin.datamodel.Displayable

enum class LabMeasurement(val display: String, val defaultUnit: LabUnit) : Displayable {
    ACTIVATED_PARTIAL_THROMBOPLASTIN_TIME_RATIO("APTT ratio", LabUnit.NONE),
    ACTIVATED_PARTIAL_THROMBOPLASTIN_TIME("APTT", LabUnit.SECONDS),
    ACTIVE_VITAMIN_B12("active vitamin B12", LabUnit.PICOMOLES_PER_LITER),
    ADRENOCORTICOTROPIC_HORMONE("ACTH", LabUnit.PICOMOLES_PER_LITER),
    ALANINE_AMINOTRANSFERASE("ALAT", LabUnit.UNITS_PER_LITER),
    ALBUMIN_CREATININE_RATIO("albumin/creatinine ratio", LabUnit.GRAMS_PER_MOLE),
    ALBUMIN_FRACTION_C("albumin fraction C", LabUnit.GRAMS_PER_LITER),
    ALBUMIN_URINE("albumin in urine", LabUnit.GRAMS_PER_LITER),
    ALBUMIN("albumin", LabUnit.GRAMS_PER_LITER),
    ALKALINE_PHOSPHATASE("ALP", LabUnit.UNITS_PER_LITER),
    ALPHA_1_ANTITRYPSIN("alpha 1 antitrypsin", LabUnit.GRAMS_PER_LITER),
    ALPHA_1_MICROGLOBULIN_CREATININE_RATIO_URINE("A1M/creatinine ratio in urine", LabUnit.GRAMS_PER_MOLE),
    ALPHA_1_MICROGLOBULIN_URINE("A1M in urine", LabUnit.MILLIGRAMS_PER_LITER),
    ALPHA_FETOPROTEIN("AFP", LabUnit.NANOGRAMS_PER_MILLILITER),
    ALPHA1_FRACTION_C("alpha 1 fraction C", LabUnit.GRAMS_PER_LITER),
    ALPHA2_FRACTION_C("alpha 2 fraction C", LabUnit.GRAMS_PER_LITER),
    AMYLASE("amylase", LabUnit.UNITS_PER_LITER),
    ANDROSTENEDIONE("androstenedione", LabUnit.NANOMOLES_PER_LITER),
    ANGIOTENSIN_CONVERTING_ENZYME_2("ACE-2", LabUnit.UNITS_PER_LITER),
    ANION_GAP("anion Gap", LabUnit.MILLIMOLES_PER_LITER),
    ANTI_EXTRACTABLE_NUCLEAR_ANTIGEN("anti-ENA", LabUnit.NONE),
    APOLIPOPROTEIN_B("apolipoprotein B", LabUnit.GRAMS_PER_LITER),
    ASPARTATE_AMINOTRANSFERASE("ASAT", LabUnit.UNITS_PER_LITER),
    BASE_EXCESS_BG("base excess (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    BASOPHIL_GRANULOCYTES_ABS("absolute basophil granulocytes count", LabUnit.BILLIONS_PER_LITER),
    BASOPHIL_GRANULOCYTES_PCT("basophil granulocytes percentage", LabUnit.PERCENTAGE),
    BCELL_PCT("percentage B-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    BETA_2_MICROGLOBULIN("B2M", LabUnit.MILLIGRAMS_PER_LITER),
    BETA_FRACTION_C("beta fraction C", LabUnit.GRAMS_PER_LITER),
    BICARBONATE("bicarbonate", LabUnit.MILLIMOLES_PER_LITER),
    BOUND_TRIIODOTHYRONINE( "bound T3", LabUnit.NANOMOLES_PER_LITER),
    C_PEPTIDE("C-Peptide", LabUnit.NANOMOLES_PER_LITER),
    C_REACTIVE_PROTEIN("CRP", LabUnit.MILLIGRAMS_PER_LITER),
    CALCITONIN("calcitonin", LabUnit.NANOGRAMS_PER_LITER),
    CALCIUM("calcium", LabUnit.MILLIMOLES_PER_LITER),
    CALPROTECTINE_WEIGHT("weight calprotectine Buhlman", LabUnit.GRAMS),
    CALPROTECTINE("calprotectine Buhlman", LabUnit.MICROGRAMS_PER_GRAM),
    CARBOHYDRATE_ANTIGEN_125("CA 125", LabUnit.KILOUNITS_PER_LITER),
    CARBOHYDRATE_ANTIGEN_15_3("CA 15.3", LabUnit.KILOUNITS_PER_LITER),
    CARBOHYDRATE_ANTIGEN_19_9("CA 19.9", LabUnit.KILOUNITS_PER_LITER),
    CARBOXYHEMOGLOBIN_F("COHb fraction", LabUnit.NONE),
    CARBOXYHEMOGLOBIN_PCT("COHb percentage", LabUnit.PERCENTAGE),
    CARBOXYHEMOGLOBIN("COHb", LabUnit.NONE),
    CARCINOEMBRYONIC_ANTIGEN("carcinoembryonic antigen", LabUnit.MICROGRAMS_PER_LITER),
    CD4_CD8_RATIO("CD4/CD8 ratio", LabUnit.NONE),
    CD4_POSITIVE_CELLS_ABS("absolute CD4+T-Cells count", LabUnit.MILLIONS_PER_LITER),
    CD4_POSITIVE_CELLS_PCT("percentage CD4+ T-cells", LabUnit.PERCENTAGE_OF_T_CELLS),
    CD8_POSITIVE_CELLS_ABS("absolute CD8+T-Cells count", LabUnit.MILLIONS_PER_LITER),
    CD8_POSITIVE_CELLS_PCT("percentage CD8+ T-cells", LabUnit.PERCENTAGE_OF_T_CELLS),
    CERULOPLASMIN("ceruloplasmin", LabUnit.GRAMS_PER_LITER),
    CHLORIDE_URINE("chloride in urine", LabUnit.MILLIMOLES_PER_LITER),
    CHLORIDE("chloride", LabUnit.MILLIMOLES_PER_LITER),
    CHOLESTEROL_HDL_RATIO("cholesterol-HDL ratio", LabUnit.NONE),
    CHOLESTEROL("cholesterol", LabUnit.MILLIMOLES_PER_LITER),
    CHROMOGRANIN_A("CgA", LabUnit.NANOGRAMS_PER_MILLILITER),
    COLLAGEN_EPINEPHRINE_CLOSURE_TIME("col/epi closure time", LabUnit.SECONDS),
    CORRECTED_CALCIUM("corrected calcium", LabUnit.MILLIMOLES_PER_LITER),
    CORTICOSTERONE("corticosterone", LabUnit.NANOMOLES_PER_LITER),
    CORTISOL_URINE("cortisol in urine", LabUnit.NANOMOLES_PER_LITER),
    CORTISOL("cortisol", LabUnit.NANOMOLES_PER_LITER),
    CREATINE_KINASE_MB("CKMB", LabUnit.MICROGRAMS_PER_LITER),
    CREATINE_KINASE("creatine Kinase", LabUnit.UNITS_PER_LITER),
    CREATININE_24U("creatinine in 24h urine", LabUnit.MILLIMOLES_PER_DAY),
    CREATININE_CLEARANCE_24H("creatinine-clearance (24h urine)", LabUnit.MILLILITERS_PER_MINUTE),
    CREATININE_CLEARANCE_CG("creatinine clearance (CG)", LabUnit.NONE),
    CREATININE_URINE("creatinine in urine", LabUnit.MILLIMOLES_PER_LITER),
    CREATININE("creatinine", LabUnit.MICROMOLES_PER_LITER),
    CT_ALBUMIN("ct Albumin", LabUnit.NONE),
    CYCLIC_CITRULLINATED_PEPTIDE_AB("CCP antibodies", LabUnit.UNITS_PER_MILLILITER),
    CYFRA_21_1("cyfra 21.1", LabUnit.MICROGRAMS_PER_LITER),
    CYIGK_CYIGL_RATIO("CyIgK/CyIgL ratio", LabUnit.NONE),
    D_DIMER("D-dimer", LabUnit.MILLIGRAMS_PER_LITER),
    DEHYDROEPIANDROSTERON_SULFATE("DHEA sulfate", LabUnit.MICROMOLES_PER_LITER),
    DEHYDROEPIANDROSTERON("DHEA", LabUnit.NANOMOLES_PER_LITER),
    DEV_POP_PCT("% deviating population", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    DIHYDROTESTOSTERONE("DHT", LabUnit.NANOMOLES_PER_LITER),
    DIRECT_BILIRUBIN("direct bilirubin", LabUnit.MICROMOLES_PER_LITER),
    DNA_CONC_A("DNA concentration A", LabUnit.MICROGRAMS_PER_MICROLITER),
    DNA_CONC_B("DNA concentration B", LabUnit.MICROGRAMS_PER_MICROLITER),
    DSDNA_ANTIBODIES("dsDNA antibodies", LabUnit.INTERNATIONAL_UNITS_PER_MILLILITER),
    EGFR_CKD_EPI("estimated GFR (CKD-EPI)", LabUnit.MILLILITERS_PER_MINUTE),
    EGFR_MDRD("estimated GFR (MDRD)", LabUnit.MILLILITERS_PER_MINUTE),
    ELASTASE_FAECES("Elastase in faeces", LabUnit.GRAMS),
    ELEVEN_DESOXYCORTISOL("DOC", LabUnit.NANOMOLES_PER_LITER),
    EOSINOPHIL_GRANULOCYTES_ABS("absolute eosinophil granulocytes count", LabUnit.BILLIONS_PER_LITER),
    EOSINOPHIL_GRANULOCYTES_LQ("eosinophil granulocytes LQ", LabUnit.MILLIONS_PER_LITER),
    EOSINOPHIL_GRANULOCYTES_PCT("eosinophil granulocytes percentage", LabUnit.PERCENTAGE),
    ERFM("rheumatoid factors", LabUnit.INTERNATIONAL_UNITS_PER_MILLILITER),
    ERYTHROBLASTS_ABS("absolute erythroblasts count", LabUnit.BILLIONS_PER_LITER),
    ERYTHROCYTE_SEDIMENTATION_RATE("ESR", LabUnit.MILLIMETERS_PER_HOUR),
    ERYTHROCYTES_ABS("absolute erythrocytes count", LabUnit.TRILLIONS_PER_LITER),
    ERYTHROCYTES_LQ("erythrocytes in liquor", LabUnit.TRILLIONS_PER_LITER),
    ESTRADIOL("estradiol", LabUnit.PICOMOLES_PER_LITER),
    EVEROLIMUS("everolimus", LabUnit.MICROGRAMS_PER_LITER),
    FACTOR_V("factor V", LabUnit.UNITS_PER_MILLILITER),
    FERRITIN("ferritin", LabUnit.MICROGRAMS_PER_LITER),
    FETAL_HEMOGLOBIN_F("HbF fraction", LabUnit.NONE),
    FETAL_HEMOGLOBIN_PCT("HbF percentage", LabUnit.PERCENTAGE),
    FIBRINOGEN("fibrinogen", LabUnit.GRAMS_PER_LITER),
    FIVE_HIAA("5-HIAA", LabUnit.NANOMOLES_PER_LITER),
    FIVE_HIAA_24U("5-HIAA in 24h urine", LabUnit.NONE),
    FIVE_HIAA_CREATININE_RATIO("5-HIAA creatinine ratio", LabUnit.MILLIMOLES_PER_MOLE),
    FIVE_HIAA_URINE("5-HIAA in urine", LabUnit.MICROMOLES_PER_LITER),
    FOLIC_ACID("folic acid", LabUnit.NANOMOLES_PER_LITER),
    FOLLICLE_STIMULATING_HORMONE("FSH", LabUnit.UNITS_PER_LITER),
    FREE_CORTISOL("free cortisol", LabUnit.NANOMOLES_PER_DAY),
    FREE_KAPPA_FREE_LAMBDA_RATIO("ratio Free Kappa / Free Lambda", LabUnit.NONE),
    FREE_KAPPA("free Kappa", LabUnit.MILLIGRAMS_PER_LITER),
    FREE_LAMBDA("free Lambda", LabUnit.MILLIGRAMS_PER_LITER),
    FREE_PROSTATE_SPECIFIC_ANTIGEN("free PSA", LabUnit.MICROGRAMS_PER_LITER),
    FREE_TESTOSTERONE( "free testosterone", LabUnit.NANOMOLES_PER_LITER),
    FREE_THYROXINE("free T4", LabUnit.PICOMOLES_PER_LITER),
    FREE_TRIIODOTHYRONINE("free T3", LabUnit.PICOMOLES_PER_LITER),
    FRL("freeze number leukemia", LabUnit.NONE),
    FVIII_ACTIVITY("FVIII activity", LabUnit.UNITS_PER_MILLILITER),
    GAAD_SCORE("GAAD-score", LabUnit.NONE),
    GAMMA_FRACTION_C("gamma fraction C", LabUnit.GRAMS_PER_LITER),
    GAMMA_GLUTAMYLTRANSFERASE("GGT", LabUnit.UNITS_PER_LITER),
    GASTRIN("gastrin", LabUnit.NANOGRAMS_PER_LITER),
    GLA("Mprot IgG-L1", LabUnit.GRAMS_PER_LITER),
    GLUCOSE_LQ("glucose in liquor", LabUnit.MILLIMOLES_PER_LITER),
    GLUCOSE("glucose", LabUnit.MILLIMOLES_PER_LITER),
    GRANULOCYTES_LQ("granulocytes in liquor", LabUnit.BILLIONS_PER_LITER),
    GROWTH_HORMONE("growth hormone", LabUnit.MICROGRAMS_PER_LITER),
    HAPTOGLOBIN("haptoglobin", LabUnit.GRAMS_PER_LITER),
    HDL_CHOLESTEROL("HDL", LabUnit.MILLIMOLES_PER_LITER),
    HEMATOCRIT("hematocrit", LabUnit.NONE),
    HEMOGLOBIN_A0("hemoglobin A0", LabUnit.PERCENTAGE),
    HEMOGLOBIN_A1C("hemoglobin A1c", LabUnit.MILLIMOLES_PER_MOLE),
    HEMOGLOBIN_E("hemoglobin E", LabUnit.PERCENTAGE),
    HEMOGLOBIN("hemoglobin", LabUnit.MILLIMOLES_PER_LITER),
    HEMOLYSIS_INDEX("hemolysis index", LabUnit.NONE),
    HFC_LQ("high fluorescent cells in liquor", LabUnit.MILLIONS_PER_LITER),
    HIGH_SENSITIVITY_TROPONIN_T("HsTnT", LabUnit.NANOGRAMS_PER_LITER),
    HUMAN_CHORIONIC_GONADOTROPIN("HCG", LabUnit.INTERNATIONAL_UNITS_PER_LITER),
    HUMAN_EPIDIDYMIS_PROTEIN_4("HE4", LabUnit.PICOMOLES_PER_LITER),
    ICTERIC_INDEX("icteric index", LabUnit.NONE),
    IGF_BP3("IGF-BP3", LabUnit.MILLIGRAMS_PER_LITER),
    IMMATURE_GRANULOCYTES_ABS("absolute immature granulocytes count", LabUnit.BILLIONS_PER_LITER),
    IMMATURE_GRANULOCYTES_PCT("immature granulocytes percentage", LabUnit.PERCENTAGE),
    IMMUNOGLOBIN_A("IgA", LabUnit.GRAMS_PER_LITER),
    IMMUNOGLOBIN_G("IgG", LabUnit.GRAMS_PER_LITER),
    IMMUNOGLOBIN_G4("IgG4", LabUnit.GRAMS_PER_LITER),
    IMMUNOGLOBIN_M("IgM", LabUnit.GRAMS_PER_LITER),
    INDIRECT_BILIRUBIN("indirect bilirubin", LabUnit.MICROMOLES_PER_LITER),
    INSPIRED_OXYGEN_FRACTION("fraction of inhaled oxygen", LabUnit.PERCENTAGE),
    INSULIN_LIKE_GROWTH_FACTOR_1_STANDARD_DEVIATION_SCORE("IGF-1 SDS", LabUnit.NONE),
    INSULIN_LIKE_GROWTH_FACTOR_1("IGF-1", LabUnit.NANOMOLES_PER_LITER),
    INSULIN("insulin", LabUnit.PICOMOLES_PER_LITER),
    INTERNATIONAL_NORMALIZED_RATIO("INR", LabUnit.NONE),
    IONIZED_CALCIUM_7_4("ionized calcium (pH 7.4)", LabUnit.MILLIMOLES_PER_LITER),
    IONIZED_CALCIUM("ionized calcium", LabUnit.MILLIMOLES_PER_LITER),
    IRON("iron", LabUnit.MICROMOLES_PER_LITER),
    LACTATE_DEHYDROGENASE_LQ("LDH in liquor", LabUnit.UNITS_PER_LITER),
    LACTATE_DEHYDROGENASE("LDH", LabUnit.UNITS_PER_LITER),
    LACTATE("lactate", LabUnit.MILLIMOLES_PER_LITER),
    LDL_CHOLESTEROL("LDL", LabUnit.MILLIMOLES_PER_LITER),
    LEUKOCYTES_ABS("absolute leukocytes count", LabUnit.BILLIONS_PER_LITER),
    LEUKOCYTES_LQ("leukocytes in liquor", LabUnit.BILLIONS_PER_LITER),
    LIPASE("lipase", LabUnit.UNITS_PER_LITER),
    LIPEMIC_INDEX("lipemic index", LabUnit.NONE),
    LITHIUM_URINE("lithium in urine", LabUnit.MILLIMOLES_PER_LITER),
    LUTEINIZING_HORMONE("LH", LabUnit.UNITS_PER_LITER),
    LYMPHOCYTES_ABS("absolute lymphocytes count", LabUnit.BILLIONS_PER_LITER),
    LYMPHOCYTES_PCT("lymphocytes percentage", LabUnit.PERCENTAGE),
    MAGNESIUM("magnesium", LabUnit.MILLIMOLES_PER_LITER),
    MEAN_CORPUSCULAR_HEMOGLOBIN_CONCENTRATION("MCHC", LabUnit.MILLIMOLES_PER_LITER),
    MEAN_CORPUSCULAR_HEMOGLOBIN("MCH", LabUnit.FEMTOMOLES),
    MEAN_CORPUSCULAR_VOLUME("MCV", LabUnit.FEMTOLITERS),
    MEAN_PLATELET_VOLUME("MPV", LabUnit.FEMTOLITERS),
    METANEPHRINE("metanephrine ", LabUnit.NANOMOLES_PER_LITER),
    METHEMOGLOBIN_F("MetHb", LabUnit.NONE),
    METHEMOGLOBIN_PCT("MetHb percentage", LabUnit.PERCENTAGE),
    MONOCYTES_ABS("absolute monocytes count", LabUnit.BILLIONS_PER_LITER),
    MONOCYTES_PCT("monocytes percentage", LabUnit.PERCENTAGE),
    MONONUCLEAR_ABS("absolute mononuclear cell count", LabUnit.MILLIONS_PER_LITER),
    MYCOPHENYLATE("mycophenylate", LabUnit.MILLIGRAMS_PER_LITER),
    MYELOCYTES_ABS("absolute myelocytes count", LabUnit.BILLIONS_PER_LITER),
    MYELOCYTES_PCT("myelocytes percentage", LabUnit.PERCENTAGE),
    MYELOPEROXIDASE_ANTIBODIES("MPO antibodies", LabUnit.INTERNATIONAL_UNITS_PER_MILLILITER),
    MYOGLOBIN("myoglobin", LabUnit.NANOMOLES_PER_LITER),
    NEURON_SPECIFIC_ENOLASE("NSE", LabUnit.MICROGRAMS_PER_LITER),
    NEUTROPHILS_ABS("absolute neutrophil count", LabUnit.BILLIONS_PER_LITER),
    NEUTROPHILS_PCT("neutrophil percentage", LabUnit.PERCENTAGE),
    NK_PCT("percentage NK-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    NON_HDL_CHOLESTEROL("non-HDL", LabUnit.NONE),
    NORMETANEPHRINE("normetanephrine", LabUnit.NANOMOLES_PER_LITER),
    NT_PRO_BNP("NT-pro-BNP", LabUnit.PICOMOLES_PER_LITER),
    O2_CONTENT_BG("O2 content (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    O2_FRACTION_BG("O2 saturation fraction (blood gas)", LabUnit.NONE),
    O2_SATURATION_BG("O2 saturation percentage (blood gas)", LabUnit.PERCENTAGE),
    OSMOLALITY_URINE("osmolality in urine", LabUnit.MILLI_OSMOLE_PER_KILOGRAM),
    OSMOLALITY("osmolality", LabUnit.MILLI_OSMOLE_PER_KILOGRAM),
    P50_BG("P50 (blood gas)", LabUnit.KILO_PASCAL),
    PARATHYROID_HORMONE_INTACT("PTH", LabUnit.PICOMOLES_PER_LITER),
    PARTIAL_PROTHROMBIN_TIME("PPT", LabUnit.SECONDS),
    PCO2_BG("pCO2 (blood gas)", LabUnit.KILO_PASCAL),
    PH_BG("pH (blood gas)", LabUnit.NONE),
    PH_OV("pH OV", LabUnit.NONE),
    PH_URINE("pH urine", LabUnit.NONE),
    PHOSPHATE("phosphate", LabUnit.MILLIMOLES_PER_LITER),
    PROTEIN_INDUCED_BY_VITAMIN_K_ABSENCE_II("PIVKA-II", LabUnit.NANOGRAMS_PER_MILLILITER),
    PLASMA_PCT("percentage plasma cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    PO2_BG("pO2 (blood gas)", LabUnit.KILO_PASCAL),
    POLYNUCLEAR_ABS("absolute polynuclear cells count", LabUnit.MILLIONS_PER_LITER),
    POTASSIUM_URINE("potassium in urine", LabUnit.MILLIMOLES_PER_LITER),
    POTASSIUM("potassium", LabUnit.MILLIMOLES_PER_LITER),
    PREC_BCELL_PCT("% precursor-B-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    PREC_MYL_PCT("% myeloid precursor-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    PRNT50_SARS_COV_2("PRNT50 SARS-CoV-2", LabUnit.PRNT50),
    PROCALCITONIN("procalcitonin", LabUnit.NANOGRAMS_PER_MILLILITER),
    PROGESTERONE_17_OH("17-OH Progesterone", LabUnit.NANOMOLES_PER_LITER),
    PROGESTERONE("progesterone", LabUnit.NANOMOLES_PER_LITER),
    PROLACTIN("prolactin", LabUnit.UNITS_PER_LITER),
    PROSTATE_SPECIFIC_ANTIGEN_RATIO("ratio PSA", LabUnit.PERCENTAGE),
    PROSTATE_SPECIFIC_ANTIGEN("PSA", LabUnit.MICROGRAMS_PER_LITER),
    PROTEINASE_3_ANTIBODIES("PR3 antibodies", LabUnit.INTERNATIONAL_UNITS_PER_MILLILITER),
    PROTHROMBIN_TIME("PT", LabUnit.SECONDS),
    RED_BLOOD_CELL_DISTRIBUTION_WIDTH("RDW", LabUnit.PERCENTAGE),
    RETICULOCYTES_ABS("absolute reticulocytes count", LabUnit.BILLIONS_PER_LITER),
    RETICULOCYTES_INDEX("reticulocyte index", LabUnit.PERCENTAGE),
    RETICULOCYTES_PCT("reticulocytes percentage", LabUnit.PERCENTAGE),
    REVERSE_TRIIODOTHYRONINE("reverse T3", LabUnit.NANOMOLES_PER_LITER),
    ROD_GRANULOCYTES_ABS("absolute rod-shaped granulocytes count", LabUnit.BILLIONS_PER_LITER),
    ROD_GRANULOCYTES_PCT("rod-shaped granulocytes percentage", LabUnit.PERCENTAGE),
    SB100("SB100", LabUnit.NANOGRAMS_PER_LITER),
    SEGMENTS_ABS("absolute segments count", LabUnit.BILLIONS_PER_LITER),
    SEGMENTS_PCT("segments percentage", LabUnit.PERCENTAGE),
    SEROTONIN("serotonin", LabUnit.MICROMOLES_PER_LITER),
    SEX_HORMONE_BINDING_GLOBULIN("SHBG", LabUnit.NANOMOLES_PER_LITER),
    SMIGK_SMIGL_RATIO("SmIgK/SmIgL ratio", LabUnit.NONE),
    SODIUM_URINE("sodium in urine", LabUnit.MILLIMOLES_PER_LITER),
    SODIUM("sodium", LabUnit.MILLIMOLES_PER_LITER),
    SOLUBLE_IL2R("soluble IL-2R", LabUnit.UNITS_PER_MILLILITER),
    SPECIFIC_WEIGHT_URINE("specific weight urine", LabUnit.KILOGRAMS_PER_LITER),
    SQUAMOUS_CELL_CARCINOMA_ANTIGEN("SCC antigen", LabUnit.MICROGRAMS_PER_LITER),
    SSA_AB("SS-A antibodies", LabUnit.UNITS_PER_MILLILITER),
    SSB_AB("SS-B antibodies", LabUnit.UNITS_PER_MILLILITER),
    TACROLIMUS("tacrolimus", LabUnit.MICROGRAMS_PER_LITER),
    TCELL_ABS("absolute T-Cells count", LabUnit.MILLIONS_PER_LITER),
    TCELL_PCT("percentage T-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    TESTOSTERONE("testosterone", LabUnit.NANOMOLES_PER_LITER),
    THREE_MT("3-MT", LabUnit.NANOMOLES_PER_LITER),
    THROMBO_CITRATE("thrombo citrate", LabUnit.BILLIONS_PER_LITER),
    THROMBOCYTES_ABS("absolute thrombocyte count", LabUnit.BILLIONS_PER_LITER),
    THYROGLOBULIN_AB("hs-Thyreoglobulin antibody", LabUnit.UNITS_PER_MILLILITER),
    THYROGLOBULIN_RECOVERY("hs-Thyreoglobulin recovery", LabUnit.PERCENTAGE),
    THYROGLOBULIN("hs-Thyreoglobulin", LabUnit.MICROGRAMS_PER_LITER),
    THYROID_STIMULATING_HORMONE("TSH", LabUnit.MILLIUNITS_PER_LITER),
    TOTAL_BILIRUBIN("total bilirubin", LabUnit.MICROMOLES_PER_LITER),
    TOTAL_PROTEIN_24U("total protein in 24h urine", LabUnit.GRAMS_PER_DAY),
    TOTAL_PROTEIN_LQ("total protein in liquor", LabUnit.GRAMS_PER_LITER),
    TOTAL_PROTEIN_URINE_CREATININE_RATIO_24H("total urine protein to creatinine ratio in 24h urine", LabUnit.MILLIGRAMS_PER_MILLIMOLE),
    TOTAL_PROTEIN_URINE_CREATININE_RATIO("total urine protein to creatinine ratio", LabUnit.MILLIGRAMS_PER_MILLIMOLE),
    TOTAL_PROTEIN_URINE("total urine protein", LabUnit.GRAMS_PER_LITER),
    TOTAL_PROTEIN("total protein", LabUnit.GRAMS_PER_LITER),
    TOTAL_THYROXINE("total T4", LabUnit.NANOMOLES_PER_LITER),
    TOTAL_TRIIODOTHYRONINE("total T3", LabUnit.PICOMOLES_PER_LITER),
    TRANSFERRIN_SATURATION("TSAT", LabUnit.PERCENTAGE),
    TRANSFERRIN("transferrin", LabUnit.GRAMS_PER_LITER),
    TRIGLYCERIDE("triglyceride", LabUnit.MILLIMOLES_PER_LITER),
    TRYPTASE("tryptase", LabUnit.MICROGRAMS_PER_LITER),
    TWENTY_ONE_DEOXYCORTISOL("21-DOC", LabUnit.NANOMOLES_PER_LITER),
    UREA_URINE("urea in urine", LabUnit.MILLIMOLES_PER_LITER),
    UREA("urea", LabUnit.MILLIMOLES_PER_LITER),
    URIC_ACID("uric acid", LabUnit.MILLIMOLES_PER_LITER),
    URINE_SPECIFIC_GRAVITY("urine specific gravity", LabUnit.NONE),
    URINE_VOLUME_24H_ENDO("24-hour volume urine for endocrinology", LabUnit.MILLILITERS),
    URINE_VOLUME_24H_SUB("24-hour volume urine for solid ", LabUnit.MILLILITERS),
    URINE_VOLUME_24H("24-hour volume urine", LabUnit.MILLILITERS),
    UROBILINOGEN_URINE("urobilinogen in urine", LabUnit.MICROMOLES_PER_LITER),
    VITAMIN_A("vitamin A", LabUnit.MICROMOLES_PER_LITER),
    VITAMIN_B3("vitamin B3", LabUnit.MICROMOLES_PER_LITER),
    VITAMIN_B12("vitamin B12", LabUnit.PICOMOLES_PER_LITER),
    VITAMIN_D_1_25_DI_OH("1.25-di-OH Vitamin D", LabUnit.PICOMOLES_PER_LITER),
    VITAMIN_D_25_OH("vitamin D 25-OH", LabUnit.NANOMOLES_PER_LITER),
    VITAMIN_E("vitamin E blood", LabUnit.MICROMOLES_PER_LITER),
    VITAMIN_K("vitamin K", LabUnit.NANOMOLES_PER_LITER),
    VON_WILLEBRAND_FACTOR_ACTIVITY("vWF activity", LabUnit.UNITS_PER_MILLILITER),
    VON_WILLEBRAND_FACTOR_ANTIGEN("vWF antigen", LabUnit.UNITS_PER_MILLILITER),
    VON_WILLEBRAND_FACTOR_COLLAGEN_BINDING("vWF collagen binding", LabUnit.UNITS_PER_MILLILITER),
    WHITE_BLOOD_CELL_COUNT("WBCC", LabUnit.MILLIONS_PER_MILLILITER),
    WHITE_BLOOD_CELL_RED_BLOOD_CELL_RATIO_LQ("white blood cell / red blood cell ratio LQ", LabUnit.PERCENTAGE),
    ZINC("zinc in whole blood", LabUnit.MICROMOLES_PER_LITER),
    UNKNOWN("unknown", LabUnit.NONE);

    override fun display(): String {
        return display
    }
}
