package com.hartwig.actin.datamodel

object IcdConstants {
    const val LEPTOMENINGEAL_METASTASES_CODE = "2D51"
    const val CHRONIC_CANCER_RELATED_PAIN_CODE = "MG30.1"
    const val ACUTE_PAIN_CODE = "MG31"
    const val HYPOKALEMIA_CODE = "5C77"
    const val HYPOMAGNESEMIA_CODE = "5C64.41"
    const val CALCIUM_DEFICIENCY_CODE = "5B5K.1"
    const val LIVER_DISEASE_BLOCK = "BlockL1-DB9"
    const val DIGESTIVE_SYSTEM_DISEASE_CHAPTER = "13"
    const val NERVOUS_SYSTEM_DISEASE_CHAPTER = "08"
    const val CIRCULATORY_SYSTEM_DISEASE_CHAPTER = "11"
    const val HYPERTENSIVE_DISEASES_BLOCK = "BlockL1-BA0"
    const val HYPOTENSION_BLOCK = "BlockL1-BA2"
    const val ISCHAEMIC_HEART_DISEASES_BLOCK = "BlockL1-BA4"
    const val PULMONARY_HEART_DISEASE_BLOCK = "BlockL1-BB0"
    const val PERICARDITIS_BLOCK = "BlockL1-BB2"
    const val ENDOCARDITIS_BLOCK = "BlockL1-BB4"
    const val HEART_VALVE_DISEASE_BLOCK = "BlockL1-BB6"
    const val DISEASES_OF_CORONARY_ARTERY_BLOCK = "BlockL1-BA8"
    const val DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK = "BlockL1-BC4"
    const val CARDIAC_ARRHYTHMIA_BLOCK = "BlockL1-BC6"
    const val HEART_FAILURE_BLOCK = "BlockL1-BD1"
    const val CONGESTIVE_HEART_FAILURE_CODE = "BD10"
    const val NYHA_CLASS_1_CODE = "XS3A"
    const val NYHA_CLASS_2_CODE = "XS6B"
    const val NYHA_CLASS_3_CODE = "XS9T"
    const val NYHA_CLASS_4_CODE = "XS9F"
    const val EYE_DISEASE_CHAPTER = "09"
    const val INTRACRANIAL_HAEMORRHAGE_BLOCK = "BlockL2-8B0"
    const val CEREBRAL_ISCHAEMIA_BLOCK = "BlockL2-8B1"
    const val STROKE_NOS_CODE = "8B20"
    const val DISSECTION_OF_CEREBRAL_ARTERY_CODE = "8B22.0"
    const val HEREDITARY_BLEEDING_DISORDER_BLOCK = "BlockL3-3B1"
    const val HEREDITARY_THROMBOPHILIA_CODE = "3B61.0"
    const val ARTERY_DISEASE_BLOCK = "BlockL1-BD3"
    const val VEIN_DISEASE_BLOCK = "BlockL1-BD7"
    const val ACUTE_MYOCARDIAL_INFARCT_CODE = "BA41"
    const val DEEP_VEIN_THROMBOSIS_CODE = "BD71"
    const val VENOUS_THROMBOEMBOLISM_CODE = "BD72"
    const val PORTAL_VEIN_THROMBOSIS_CODE = "DB98.3"
    const val SPLENIC_VEIN_THROMBOSIS_CODE = "DB98.4"
    const val CEREBRAL_VENOUS_THROMBOSIS = "8B22.1"
    const val INTRACARDIAC_THROMBOSIS = "BC46"
    const val ACUTE_ARTERIAL_OCCLUSION_CODE = "BD30"
    const val CHOLESTEROL_ATHEROEMBOLISM_CODE = "BD53.4"
    const val PULMONARY_THROMBOEMBOLISM_CODE = "BB00"
    const val CERTAIN_LOWER_RESPIRATORY_TRACT_DISEASES_BLOCK = "BlockL1-CA2"
    const val CERTAIN_DISEASES_OF_RESPIRATORY_SYSTEM_CODE = "CB40"
    const val LUNG_INFECTIONS_BLOCK = "BlockL1-CA4"
    const val LUNG_ABSCESS_CODE = "CA43"
    const val LUNG_DISEASES_DUE_TO_EXTERNAL_AGENTS_BLOCK = "BlockL1-CA6"
    const val PNEUMONITIS_DUE_TO_EXTERNAL_AGENTS_BLOCK = "BlockL2-CA7"
    const val IDIOPATHIC_INTERSTITIAL_PNEUMONITIS_CODE = "CB03"
    const val IDIOPATHIC_EOSINOPHILIC_PNEUMONITIS_CODE = "CB02.1"
    const val RADIATION_PNEUMONITIS_CODE = "CA82.0"
    const val ACUTE_DRUG_INDUCED_INTERSITIAL_LUNG_DISEASE_CODE = "CA82.2"
    const val CHRONIC_DRUG_INDUCED_INTERSITIAL_LUNG_DISEASE_CODE = "CA82.3"
    const val LUNG_INTERSTITIAL_DISEASES_BLOCK = "BlockL1-CB0"
    const val PNEUMOTHORAX_CODE = "CB21"
    const val HAEMATOTHORAX_CODE = "CB26"
    const val RESPIRATORY_FAILURE_CODE = "CB41"
    const val NON_ORGAN_SPECIFIC_AUTOIMMUNE_BLOCK = "BlockL1-4A4"
    const val AUTOINFLAMMATORY_DISORDERS_BLOCK = "BlockL1-4A6"
    const val SARCOIDOSIS_CODE = "4B20"
    const val AUTOIMMUNE_THYROIDITIS_CODE = "5A03.2"
    const val AUTOIMMUNE_MYOPATHY_CODE = "8C81"
    const val AUTOIMMUNE_DISEASE_AUTONOMIC_NERVE_SYSTEM_CODE = "8D82"
    const val AUTOIMMUNE_LIVER_DISEASE_CODE = "DB96"
    const val AUTOIMMUNE_PANCREATITIS_CODE = "DC33"
    const val VASCULITIS_CODE = "4A44"
    const val RHEUMATOID_ARTHRITIS_CODE = "FA20"
    const val DIABETES_MELLITUS_BLOCK = "BlockL2-5A1"
    const val TYPE_1_DIABETES_CODE = "5A10"
    const val MULTIPLE_SCLEROSIS_CODE = "8A40"
    const val PSORIASIS_CODE = "EA90"
    const val INFLAMMATORY_BOWEL_DISEASE_BLOCK = "BlockL1-DD7"
    const val GILBERT_SYNDROME_CODE = "5C58.01"
    const val DISEASES_OF_STOMACH_OR_DUODENUM_BLOCK = "BlockL1-DA4"
    const val DISEASES_OF_SMALL_INTESTINE_BLOCK = "BlockL1-DA9"
    const val DISEASES_OF_LARGE_INTESTINE_BLOCK = "BlockL1-DB3"
    const val FUNCTIONAL_GASTROINTESTINAL_DISEASE_BLOCK = "BlockL1-DD9"
    const val DIVERTICULITIS_SMALL_INTESTINE_CODE = "DC70"
    const val DIVERTICULITIS_LARGE_INTESTINE_CODE = "DC80"
    const val GASTROENTERITIS_AND_COLITIS_BLOCK = "BlockL1-1A0"
    const val DISEASES_OF_ESOPHAGUS_BLOCK = "BlockL1-DA2"
    const val KIDNEY_FAILURE_BLOCK = "BlockL2-GB6"
    const val LIVER_CIRRHOSIS_CODE = "DB93.1"
    const val PRESENCE_OF_DEVICE_IMPLANT_OR_GRAFT_BLOCK = "BlockL2-QB5"
    const val LONG_QT_SYNDROME_CODE = "BC65.0"
    const val FAMILY_HISTORY_OF_OTHER_SPECIFIED_HEALTH_PROBLEMS_CODE = "QC6Y"
    const val FAMILY_HISTORY_OF_UNSPECIFIED_HEALTH_PROBLEMS_CODE = "QC6Z"
    const val FAMILY_HISTORY_OF_CARDIOVASCULAR_DISEASE_CODE = "QC67"
    const val EPSTEIN_BARR_MONONUCLEOSIS_CODE = "1D81.0"
    const val ACUTE_HEPATITIS_A_CODE = "1E50.0"
    const val ACUTE_HEPATITIS_B_CODE = "1E50.1"
    const val CHRONIC_HEPATITIS_B_CODE = "1E51.0"
    const val ACUTE_HEPATITIS_C_CODE = "1E50.2"
    const val CHRONIC_HEPATITIS_C_CODE = "1E51.1"
    const val HIV_BLOCK = "BlockL1-1C6"
    const val HSV_CODE = "1F00"
    const val ANOGENITAL_HERPES_SIMPLEX_INFECTION_CODE = "1A94"
    const val CYTOMEGALOVIRAL_DISEASE_CODE = "1D82"
    const val TUBERCULOSIS_BLOCK = "BlockL2-1B1"
    const val ALLERGIC_OR_HYPERSENSITIVITY_CONDITIONS_BLOCK = "BlockL1-4A8"
    const val ALLERGIC_OR_HYPERSENSITIVITY_CONDITIONS_OF_UNSPECIFIED_TYPE = "4A8Z"
    const val DRUG_ALLERGY_CODE = "4A85.0"
    const val HISTORY_OF_DRUG_OR_BIOLOGICAL_SUBSTANCE_ALLERGY_CODE = "QC44.2"
    const val ADVERSE_CUTANEOUS_REACTION_TO_MEDICATION_BLOCK = "BlockL1-EH6"
    const val ANAPHYLAXIS_CODE = "4A84"
    const val DRUG_INDUCED_ANAPHYLAXIS_CODE = "4A84.1"
    const val HARMFUL_EFFECTS_OF_DRUGS_CODE = "NE60"
    const val INJURY_OR_HARM_DUE_TO_CORRECTLY_USED_DRUG_CODE = "PL13.2"
    const val ANTI_NEOPLASTIC_AGENTS = "http://id.who.int/icd/release/11/mms/2064976967"
    const val PLATINUM_COMPOUND_CODE = "XM40B7"
    const val TAXANE_CODE = "XM05L1"
    const val PD_L1_PD_1_INHIBITOR_MONOCLONAL_ANTIBODY_OR_ADC_CODE = "XM9ND9"
    const val PEMBROLIZUMAB_CODE = "XM8UG5"
    const val NIVOLUMAB_CODE = "XM6M26"
    const val ATEZOLIZUMAB_CODE = "XM8SU2"
    const val DURVALUMAB_CODE = "XM7NY5"
    const val AVELUMAB_CODE = "XM2065"
    const val CEMIPLIMAB_CODE = "XM9Z80"
    const val CEFAMYCIN_ANTIBIOTIC = "XM8J52"
    const val MONOCLONAL_ANTIBODY_BLOCK = "http://id.who.int/icd/release/11/mms/252952104"
    const val MONOCLONAL_ANTIBODY_AND_ANTIBODY_DRUG_CONJUGATE_CODE = "XM1JG6"
    const val INTERLEUKIN_INHIBITOR_CODE = "XM5ZL1"
    const val PRESENCE_OF_TRANSPLANTED_KIDNEY_CODE = "QB63.0"
    const val PRESENCE_OF_TRANSPLANTED_HEART_CODE = "QB63.1"
    const val PRESENCE_OF_TRANSPLANTED_LUNG_CODE = "QB63.2"
    const val PRESENCE_OF_TRANSPLANTED_LIVER_CODE = "QB63.3"
    const val PRESENCE_OF_TRANSPLANTED_BONE_MARROW_CODE = "QB63.6"
    const val PRESENCE_OF_TRANSPLANTED_STEM_CELL_CODE = "QB63.8"
    const val UNSPECIFIED_INFECTION_CODE = "1H0Z"
    const val ULCERATIVE_GINGIVITIS_CODE = "1C1H"
    const val CONJUNCTIVA_ULCER_CODE = "9A60.30"
    const val CORNEAL_ULCER_CODE = "9A76"
    const val DIABETIC_FOOT_ULCER_CODE = "BD54"
    const val VENOUS_LEG_ULCER_CODE = "BD74.3"
    const val ORAL_ULCER_CODE = "DA01.1"
    const val ULCERATIVE_PERIODONTITIS_CODE = "DA0C.30"
    const val GINGIVAL_ULCER_CODE = "DA0D.5"
    const val BARRETT_ULCER_CODE = "DA23.2"
    const val ESOPHAGEAL_ULCER_CODE = "DA25"
    const val STOMACH_DUODENUM_ULCER_BLOCK = "BlockL2-DA6"
    const val SMALL_INTESTINE_ULCER_CODE = "DA94"
    const val COLON_ULCER_CODE = "DB33.0"
    const val RECTAL_ULCER_CODE = "DB34.4"
    const val ANAL_ULCER_CODE = "DB52"
    const val ULCERATIVE_COLITIS_CODE = "DD71"
    const val NEUROPATHIC_SKIN_ULCER_CODE = "ED30.0"
    const val ISCHEMIC_SKIN_ULCER_CODE = "EF60"
    const val PRESSURE_ULCER_CODE = "EH90"
    const val VULVA_ULCER_CODE = "GA00.3"
    const val VAGINAL_ULCER_CODE = "GA02.3"
    const val ULCERATIVE_DISORDER_VULVA_CODE = "GA41"
    const val ULCERATIVE_DISORDER_PENIS_CODE = "GA80"
    const val DIGESTIVE_SYSTEM_ULCER_CODE = "ME24.5"
    const val ULCER_OF_SKIN_UNCERTAIN_NATURE_CODE = "ME60.2"
    const val ESOPHAGEAL_VARICES_BLEEDING = "DA26.00"
    const val UTERINE_VAGINAL_BLEEDING_BLOCK = "BlockL2-GA2"
    const val GASTROINTESTINAL_BLEEDING_CODE = "ME24.9"
    const val ORBIT_HAEMORRHAGE_CODE = "9A25.4"
    const val CONJUNCTIVAL_HAEMORRHAGE_CODE = "9A61.5"
    const val CHOROIDAL_HAEMORRHAGE_CODE = "9B63"
    const val RETINAL_HAEMORRHAGE_CODE = "9B78.5"
    const val VITREOUS_HAEMORRHAGE_CODE = "9B83"
    const val ESOPHAGEAL_HAEMORRHAGE_CODE = "DA26.2"
    const val HEPATIC_HAERMORRHAGE_CODE = "DB98.A"
    const val BILE_DUCT_HAEMORRHAGE_CODE = "DC14.0"
    const val SMALL_INTESTINE_DIVERTICULOSIS_BLEEDING_CODE = "DC71.0"
    const val SMALL_INTESTINAL_DIVERTICULAR_BLEEDING_CODE = "DC72.0"
    const val LARGE_INTESTINE_DIVERTICULOSIS_BLEEDING_CODE = "DC81.0"
    const val LARGE_INTESTINAL_DIVERTICULAR_BLEEDING_CODE = "DC82.0"
    const val UNSPECIFIED_INTESTINE_DIVERTICULOSIS_BLEEDING_CODE = "DD01.0"
    const val UNSPECIFIED_INTESTINAL_DIVERTICULAR_BLEEDING_CODE = "DD02.0"
    const val PROSTATE_HAEMORRHAGE_CODE = "GA91.4"
    const val OBSTETRIC_HAEMORRHAGE_BLOCK = "BlockL1-JA4"
    const val RESPIRATORY_PASSAGES_HAEMORRHAGE_BLOCK = "BlockL3-MD2"
    const val DIGESTIVE_SYSTEM_HAEMORRHAGE_NOS_CODE = "ME24.A"
    const val HAEMORRHAGE_NOS = "MG27"
    const val TRAUMATIC_ORBITAL_HAEMORRHAGE_CODE = "NA06.3"
    const val TRAUMATIC_RETINAL_HAEMORRHAGE_CODE = "NA06.7"
    const val TRAUMATIC_INTRACEREBRAL_HAEMORRHAGE_CODE = "NA07.1"
    const val FOCAL_CEREBELLAR_HAEMORRHAGE_CODE = "NA07.45"
    const val FOCAL_BRAIN_STEM_HAEMORRHAGE_CODE = "NA07.49"
    const val TRAUMATIC_EPIDURAL_HAEOMORRHAGE_CODE = "NA07.5"
    const val TRAUMATIC_SUBDURAL_HAEMORRHAGE_CODE = "NA07.6"
    const val TRAUMATIC_SUBARACHNOID_HAEMORRHAGE_CODE = "NA07.7"
    const val TRAUMATIC_BRAIN_HAEMORRHAGE_CODE = "NA07.8"
    const val COMPLEX_HEAD_WOUNDS_WITH_HAEMORRHAGE_CODE = "NA0A.01"
    const val RETROPERITONEAL_HAEMORRHAGE_CODE = "NB97.0"
    const val PROCEDURE_RELATED_HAEMORRHAGE_CODE = "NE81.0"
    const val OPEN_HEAD_WOUND_CODE = "NA01"
    const val OPEN_EYELID_WOUND_CODE = "NA06.04"
    const val ORBIT_WOUND_CODE = "NA06.1"
    const val COMPLEX_HEAD_WOUNDS_CODE = "NA0A.0"
    const val OPEN_NECK_WOUND_CODE = "NA21"
    const val OPEN_THORAX_WOUND_CODE = "NA81"
    const val OPEN_ABDOMEN_BACK_PELVIS_WOUND_CODE = "NB51"
    const val OPEN_SHOULDER_ARM_WOUND_CODE = "NC11"
    const val OPEN_FOREARM_WOUND_CODE = "NC31"
    const val OPEN_HAND_WOUND_CODE = "NC52"
    const val OPEN_HIP_WOUND_CODE = "NC71"
    const val OPEN_KNEE_LEG_WOUND_CODE = "NC91"
    const val OPEN_ANKLE_FOOT_WOUND_CODE = "ND12"
    const val OPEN_WOUND_MULTIPLE_REGIONS_CODE = "ND31"
    const val OPEN_WOUND_UNSPECIFIED_REGION_CODE = "ND56.1"
    const val SKULL_FACIAL_FRACTURE_CODE = "NA02"
    const val NECK_FRACTURE_CODE = "NA22"
    const val RIB_STERNUM_THORACIC_SPINE_FRACTURE_CODE = "NA82"
    const val LUMBAR_SPINE_PELVIS_FRACTURE_CODE = "NB52"
    const val SHOULDER_ARM_FRACTURE_CODE = "NC12"
    const val FOREARM_FRACTURE_CODE = "NC32"
    const val HAND_FRACTURE_CODE = "NC53"
    const val FEMUR_FRACTURE_CODE = "NC72"
    const val LOWER_LEG_FRACTURE_CODE = "NC92"
    const val FOOT_FRACTURE_CODE = "ND13"
    const val MULTIPLE_REGIONS_FRACTURE_CODE = "ND32"
    const val SPINE_FRACTURE_UNSPECIFIED_LEVEL_CODE = "ND50"
    const val ARM_FRACTURE_UNSPECIFIED_LEVEL_CODE = "ND52"
    const val LEG_FRACTURE_UNSPECIFIED_LEVEL_CODE = "ND54"
    const val FRACTURE_UNSPECIFIED_REGION_CODE = "ND56.2"
    const val FUNCTIONAL_SWALLOWING_DISORDER_CODE = "DD90.1"
    const val DISORDERS_OF_ORAL_MUCOSA_CODE = "DA01"
    const val DEPENDENCE_ON_RENAL_DIALYSIS_CODE = "QB42"
    const val DIALYSIS_CARE_CODE = "QB94"
    const val MALIGNANT_NEOPLASM_METASTASIS_IN_PLEURA_CODE = "2D72"
    const val PLEURAL_EFFUSION_CODE = "CB27"
    const val PLEURISY_CODE = "MD31"
    const val MALIGNANT_NEORPLASM_METASTASIS_IN_RETROPERITONEUM_OR_PERITONEUM_BLOCK = "BlockL3-2D9"
    const val ASCITES_CODE = "ME04"
    const val FISTULA_OF_SMALL_INTESTINE = "DA92.0"
    const val FISTULA_OF_LARGE_INTESTINE = "DB31.0"
    const val FISTULA_OF_APPENDIX = "DB11.4"
    const val GASTRIC_FISTULA = "DA40.1"
    const val FISTULA_OF_OESOPHAGUS = "DA20.Y"
    const val PRIMARY_IMMUNODEFICIENCIES_BLOCK = "BlockL1-4A0"
    const val ACQUIRED_IMMUNODEFICIENCIES = "4A20"
    const val IMMUNE_SYSTEM_DISORDERS_INVOLVING_WHITE_CELL_LINEAGES_BLOCK = "BlockL1-4B0"
    const val DISEASES_OF_IMMUNE_SYSTEM_UNSPECIFIED = "4B4Z"
    const val OTHER_SPECIFIED_DISEASES_OF_IMMUNE_SYSTEM = "4B4Y"
    const val THYMOMA_IMMUNODEFICIENCY = "4B40.2"

    val DRUG_ALLERGY_SET = setOf(
        ALLERGIC_OR_HYPERSENSITIVITY_CONDITIONS_BLOCK,
        HISTORY_OF_DRUG_OR_BIOLOGICAL_SUBSTANCE_ALLERGY_CODE,
        ADVERSE_CUTANEOUS_REACTION_TO_MEDICATION_BLOCK,
        HARMFUL_EFFECTS_OF_DRUGS_CODE,
        INJURY_OR_HARM_DUE_TO_CORRECTLY_USED_DRUG_CODE
    )

    val IMMUNOTHERAPY_DRUG_SET = setOf(
        MONOCLONAL_ANTIBODY_BLOCK,
        MONOCLONAL_ANTIBODY_AND_ANTIBODY_DRUG_CONJUGATE_CODE,
        INTERLEUKIN_INHIBITOR_CODE
    )

    val PD_L1_PD_1_DRUG_SET = setOf(
        PD_L1_PD_1_INHIBITOR_MONOCLONAL_ANTIBODY_OR_ADC_CODE,
        PEMBROLIZUMAB_CODE,
        NIVOLUMAB_CODE,
        ATEZOLIZUMAB_CODE,
        DURVALUMAB_CODE,
        AVELUMAB_CODE,
        CEMIPLIMAB_CODE
    )

    val HEART_DISEASE_SET = setOf(
        ISCHAEMIC_HEART_DISEASES_BLOCK,
        PULMONARY_HEART_DISEASE_BLOCK,
        PERICARDITIS_BLOCK,
        ENDOCARDITIS_BLOCK,
        HEART_VALVE_DISEASE_BLOCK,
        DISEASES_OF_CORONARY_ARTERY_BLOCK,
        DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK,
        CARDIAC_ARRHYTHMIA_BLOCK,
        HEART_FAILURE_BLOCK
    )

    val STROKE_SET = setOf(
        INTRACRANIAL_HAEMORRHAGE_BLOCK,
        CEREBRAL_ISCHAEMIA_BLOCK,
        STROKE_NOS_CODE,
        DISSECTION_OF_CEREBRAL_ARTERY_CODE
    )

    val THROMBOEMBOLIC_EVENT_SET = setOf(
        DEEP_VEIN_THROMBOSIS_CODE,
        VENOUS_THROMBOEMBOLISM_CODE,
        PORTAL_VEIN_THROMBOSIS_CODE,
        SPLENIC_VEIN_THROMBOSIS_CODE,
        CEREBRAL_VENOUS_THROMBOSIS,
        INTRACARDIAC_THROMBOSIS,
        ACUTE_ARTERIAL_OCCLUSION_CODE,
        CHOLESTEROL_ATHEROEMBOLISM_CODE,
        PULMONARY_THROMBOEMBOLISM_CODE
    )

    val ARTERIAL_THROMBOEMBOLIC_EVENT_SET = setOf(
        ACUTE_MYOCARDIAL_INFARCT_CODE,
        ACUTE_ARTERIAL_OCCLUSION_CODE,
        CHOLESTEROL_ATHEROEMBOLISM_CODE,
        INTRACARDIAC_THROMBOSIS
    )

    val VENOUS_THROMBOEMBOLIC_EVENT_SET = setOf(
        PULMONARY_THROMBOEMBOLISM_CODE,
        DEEP_VEIN_THROMBOSIS_CODE,
        VENOUS_THROMBOEMBOLISM_CODE,
        PORTAL_VEIN_THROMBOSIS_CODE,
        SPLENIC_VEIN_THROMBOSIS_CODE,
        CEREBRAL_VENOUS_THROMBOSIS
    )

    val RESPIRATORY_COMPROMISE_SET = setOf(
        CERTAIN_LOWER_RESPIRATORY_TRACT_DISEASES_BLOCK,
        LUNG_DISEASES_DUE_TO_EXTERNAL_AGENTS_BLOCK,
        PNEUMONITIS_DUE_TO_EXTERNAL_AGENTS_BLOCK,
        LUNG_INTERSTITIAL_DISEASES_BLOCK,
        PNEUMOTHORAX_CODE,
        HAEMATOTHORAX_CODE,
        RESPIRATORY_FAILURE_CODE,
        CERTAIN_DISEASES_OF_RESPIRATORY_SYSTEM_CODE,
        LUNG_ABSCESS_CODE
    )

    val INTERSTITIAL_LUNG_DISEASE_SET = setOf(
        LUNG_INTERSTITIAL_DISEASES_BLOCK,
        ACUTE_DRUG_INDUCED_INTERSITIAL_LUNG_DISEASE_CODE,
        CHRONIC_DRUG_INDUCED_INTERSITIAL_LUNG_DISEASE_CODE
    )

    val AUTOIMMUNE_DISEASE_SET = setOf(
        NON_ORGAN_SPECIFIC_AUTOIMMUNE_BLOCK,
        AUTOINFLAMMATORY_DISORDERS_BLOCK,
        SARCOIDOSIS_CODE,
        AUTOIMMUNE_THYROIDITIS_CODE,
        AUTOIMMUNE_MYOPATHY_CODE,
        AUTOIMMUNE_DISEASE_AUTONOMIC_NERVE_SYSTEM_CODE,
        AUTOIMMUNE_LIVER_DISEASE_CODE,
        AUTOIMMUNE_PANCREATITIS_CODE,
        VASCULITIS_CODE,
        RHEUMATOID_ARTHRITIS_CODE,
        TYPE_1_DIABETES_CODE,
        MULTIPLE_SCLEROSIS_CODE,
        PSORIASIS_CODE,
        INFLAMMATORY_BOWEL_DISEASE_BLOCK
    )

    val POSSIBLE_ABSORPTION_DIFFICULTIES_SET = setOf(
        DISEASES_OF_LARGE_INTESTINE_BLOCK,
        DISEASES_OF_SMALL_INTESTINE_BLOCK,
        DISEASES_OF_STOMACH_OR_DUODENUM_BLOCK,
        FUNCTIONAL_GASTROINTESTINAL_DISEASE_BLOCK,
        DIVERTICULITIS_LARGE_INTESTINE_CODE,
        DIVERTICULITIS_SMALL_INTESTINE_CODE,
        GASTROENTERITIS_AND_COLITIS_BLOCK,
        DISEASES_OF_ESOPHAGUS_BLOCK
    )

    val TRANSPLANTATION_SET = setOf(
        PRESENCE_OF_TRANSPLANTED_KIDNEY_CODE,
        PRESENCE_OF_TRANSPLANTED_HEART_CODE,
        PRESENCE_OF_TRANSPLANTED_LUNG_CODE,
        PRESENCE_OF_TRANSPLANTED_LIVER_CODE,
        PRESENCE_OF_TRANSPLANTED_BONE_MARROW_CODE,
        PRESENCE_OF_TRANSPLANTED_STEM_CELL_CODE
    )

    val ULCER_SET = setOf(
        ULCERATIVE_GINGIVITIS_CODE,
        CONJUNCTIVA_ULCER_CODE,
        CORNEAL_ULCER_CODE,
        DIABETIC_FOOT_ULCER_CODE,
        VENOUS_LEG_ULCER_CODE,
        ORAL_ULCER_CODE,
        ULCERATIVE_PERIODONTITIS_CODE,
        GINGIVAL_ULCER_CODE,
        BARRETT_ULCER_CODE,
        ESOPHAGEAL_ULCER_CODE,
        STOMACH_DUODENUM_ULCER_BLOCK,
        SMALL_INTESTINE_ULCER_CODE,
        COLON_ULCER_CODE,
        RECTAL_ULCER_CODE,
        ANAL_ULCER_CODE,
        ULCERATIVE_COLITIS_CODE,
        NEUROPATHIC_SKIN_ULCER_CODE,
        ISCHEMIC_SKIN_ULCER_CODE,
        PRESSURE_ULCER_CODE,
        VULVA_ULCER_CODE,
        VAGINAL_ULCER_CODE,
        ULCERATIVE_DISORDER_VULVA_CODE,
        ULCERATIVE_DISORDER_PENIS_CODE,
        DIGESTIVE_SYSTEM_ULCER_CODE,
        ULCER_OF_SKIN_UNCERTAIN_NATURE_CODE
    )

    val BLEEDING_SET = setOf(
        INTRACRANIAL_HAEMORRHAGE_BLOCK,
        ESOPHAGEAL_VARICES_BLEEDING,
        UTERINE_VAGINAL_BLEEDING_BLOCK,
        GASTROINTESTINAL_BLEEDING_CODE,
        ORBIT_HAEMORRHAGE_CODE,
        CONJUNCTIVAL_HAEMORRHAGE_CODE,
        CHOROIDAL_HAEMORRHAGE_CODE,
        RETINAL_HAEMORRHAGE_CODE,
        VITREOUS_HAEMORRHAGE_CODE,
        ESOPHAGEAL_HAEMORRHAGE_CODE,
        HEPATIC_HAERMORRHAGE_CODE,
        BILE_DUCT_HAEMORRHAGE_CODE,
        SMALL_INTESTINE_DIVERTICULOSIS_BLEEDING_CODE,
        SMALL_INTESTINAL_DIVERTICULAR_BLEEDING_CODE,
        LARGE_INTESTINE_DIVERTICULOSIS_BLEEDING_CODE,
        LARGE_INTESTINAL_DIVERTICULAR_BLEEDING_CODE,
        UNSPECIFIED_INTESTINE_DIVERTICULOSIS_BLEEDING_CODE,
        UNSPECIFIED_INTESTINAL_DIVERTICULAR_BLEEDING_CODE,
        PROSTATE_HAEMORRHAGE_CODE,
        OBSTETRIC_HAEMORRHAGE_BLOCK,
        RESPIRATORY_PASSAGES_HAEMORRHAGE_BLOCK,
        DIGESTIVE_SYSTEM_HAEMORRHAGE_NOS_CODE,
        HAEMORRHAGE_NOS,
        TRAUMATIC_ORBITAL_HAEMORRHAGE_CODE,
        TRAUMATIC_RETINAL_HAEMORRHAGE_CODE,
        TRAUMATIC_INTRACEREBRAL_HAEMORRHAGE_CODE,
        FOCAL_CEREBELLAR_HAEMORRHAGE_CODE,
        FOCAL_BRAIN_STEM_HAEMORRHAGE_CODE,
        TRAUMATIC_EPIDURAL_HAEOMORRHAGE_CODE,
        TRAUMATIC_SUBDURAL_HAEMORRHAGE_CODE,
        TRAUMATIC_SUBARACHNOID_HAEMORRHAGE_CODE,
        TRAUMATIC_BRAIN_HAEMORRHAGE_CODE,
        COMPLEX_HEAD_WOUNDS_WITH_HAEMORRHAGE_CODE,
        RETROPERITONEAL_HAEMORRHAGE_CODE,
        PROCEDURE_RELATED_HAEMORRHAGE_CODE
    )

    val WOUND_SET = setOf(
        OPEN_HEAD_WOUND_CODE,
        OPEN_EYELID_WOUND_CODE,
        ORBIT_WOUND_CODE,
        COMPLEX_HEAD_WOUNDS_CODE,
        OPEN_NECK_WOUND_CODE,
        OPEN_THORAX_WOUND_CODE,
        OPEN_ABDOMEN_BACK_PELVIS_WOUND_CODE,
        OPEN_SHOULDER_ARM_WOUND_CODE,
        OPEN_FOREARM_WOUND_CODE,
        OPEN_HAND_WOUND_CODE,
        OPEN_HIP_WOUND_CODE,
        OPEN_KNEE_LEG_WOUND_CODE,
        OPEN_ANKLE_FOOT_WOUND_CODE,
        OPEN_WOUND_MULTIPLE_REGIONS_CODE,
        OPEN_WOUND_UNSPECIFIED_REGION_CODE
    )

    val BONE_FRACTURE_SET = setOf(
        SKULL_FACIAL_FRACTURE_CODE,
        NECK_FRACTURE_CODE,
        RIB_STERNUM_THORACIC_SPINE_FRACTURE_CODE,
        LUMBAR_SPINE_PELVIS_FRACTURE_CODE,
        SHOULDER_ARM_FRACTURE_CODE,
        FOREARM_FRACTURE_CODE,
        HAND_FRACTURE_CODE,
        FEMUR_FRACTURE_CODE,
        LOWER_LEG_FRACTURE_CODE,
        FOOT_FRACTURE_CODE,
        MULTIPLE_REGIONS_FRACTURE_CODE,
        SPINE_FRACTURE_UNSPECIFIED_LEVEL_CODE,
        ARM_FRACTURE_UNSPECIFIED_LEVEL_CODE,
        LEG_FRACTURE_UNSPECIFIED_LEVEL_CODE,
        FRACTURE_UNSPECIFIED_REGION_CODE
    )

    val IMMUNO_DEFICIENCY_SET = setOf(
        PRIMARY_IMMUNODEFICIENCIES_BLOCK,
        ACQUIRED_IMMUNODEFICIENCIES,
        IMMUNE_SYSTEM_DISORDERS_INVOLVING_WHITE_CELL_LINEAGES_BLOCK,
        DISEASES_OF_IMMUNE_SYSTEM_UNSPECIFIED,
        OTHER_SPECIFIED_DISEASES_OF_IMMUNE_SYSTEM,
        THYMOMA_IMMUNODEFICIENCY,
        HIV_BLOCK
    )
}

