package com.hartwig.actin.doid

object DoidConstants {
    const val ACANTHOMA_LARGE_CELL_DOID = "4321"
    const val AMPULLA_OF_VATER_SMALL_CELL_CARCINOMA_DOID = "7136"
    const val BARTHOLINS_GLAND_SMALL_CELL_CARCINOMA_DOID = "7140"
    const val BENIGN_NEOPLASM_DOID = "0060072"
    const val BLADDER_SMALL_CELL_CARCINOMA_DOID = "0080902"
    const val BONE_CANCER_DOID = "184"
    const val BONE_MARROW_CANCER_DOID = "4960"
    const val BRAIN_CANCER_DOID = "1319"
    const val BREAST_CANCER_DOID = "1612"
    const val BREAST_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID = "6657"
    const val BREAST_LARGE_CELL_KERATINIZING_VARIANT_SQUAMOUS_CELL_CARCINOMA_DOID = "7461"
    const val BRONCHUS_CANCER_DOID = "1325"
    const val CANCER_DOID = "162"
    const val CENTRAL_NERVOUS_SYSTEM_HEMATOLOGIC_CANCER_DOID = "5772"
    const val CERVIX_SMALL_CELL_CARCINOMA_DOID = "6740"
    const val CERVIX_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID = "6659"
    const val CNS_CANCER_DOID = "3620"
    const val COLON_SMALL_CELL_CARCINOMA_DOID = "6727"
    const val COLORECTAL_CANCER_DOID = "9256"
    const val DENDRITIC_CELL_THYMOMA_DOID = "3282"
    const val ENDOMETRIAL_SMALL_CELL_CARCINOMA_DOID = "7139"
    const val ESOPHAGUS_SMALL_CELL_CARCINOMA_DOID = "7134"
    const val ESTROGEN_NEGATIVE_BREAST_CANCER_DOID = "0060076"
    const val ESTROGEN_POSITIVE_BREAST_CANCER_DOID = "0060075"
    const val EXTRAHEPATIC_BILE_DUCT_SMALL_CELL_ADENOCARCINOMA_DOID = "5926"
    const val GALLBLADDER_SMALL_CELL_CARCINOMA_DOID = "7133"
    const val GASTRIC_SMALL_CELL_CARCINOMA_DOID = "6552"
    const val GLIOBLASTOMA_DOID = "3068"
    const val HEAD_AND_NECK_CANCER_DOID = "11934"
    const val HEMATOLOGIC_CANCER_DOID = "2531"
    const val HER2_NEGATIVE_BREAST_CANCER_DOID = "0060080"
    const val HER2_POSITIVE_BREAST_CANCER_DOID = "0060079"
    const val HISTIOCYTIC_AND_DENDRITIC_CELL_CANCER_DOID = "5621"
    const val LARGE_CELL_CARCINOMA = "4552"
    const val LARGE_CELL_CARCINOMA_WITH_RHABDOID_PHENOTYPE_DOID = "7480"
    const val LARYNGEAL_SMALL_CELL_CARCINOMA_DOID = "7144"
    const val LEUKEMIA_DOID = "1240"
    const val LEUKEMIA_T_CELL_LARGE_GRANULAR_LYMPHOCYTE_DOID = "0050751"
    const val LIVER_CANCER_DOID = "3571"
    const val LUNG_ADENOCARCINOMA_DOID = "3910"
    const val LUNG_ADENOSQUAMOUS_CARCINOMA_DOID = "4829"
    const val LUNG_CANCER_DOID = "1324"
    const val LUNG_CARCINOMA_DOID = "3905"
    const val LUNG_COMBINED_TYPE_SMALL_CELL_ADENOCARCINOMA_DOID = "0050917"
    const val LUNG_COMBINED_TYPE_SMALL_CELL_CARCINOMA_DOID = "5421"
    const val LUNG_COMBINED_TYPE_LARGE_CELL_CARCINOMA_DOID = "7207"
    const val LUNG_HILUM_CANCER_DOID = "7696"
    const val LUNG_LARGE_CELL_CARCINOMA_DOID = "4556"
    const val LUNG_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID = "0050872"
    const val LUNG_MIXED_SMALL_CELL_AND_SQUAMOUS_CELL_CARCINOMA_DOID = "7081"
    const val LUNG_NON_SMALL_CELL_CARCINOMA_DOID = "3908"
    const val LUNG_NON_SQUAMOUS_NON_SMALL_CARCINOMA_DOID = "0080521"
    const val LUNG_OCCULT_SMALL_CELL_CARCINOMA_DOID = "5414"
    const val LUNG_OCCULT_LARGE_CELL_CARCINOMA_DOID = "7169"
    const val LUNG_SARCOMA_DOID = "10124"
    const val LUNG_SMALL_CELL_CARCINOMA_DOID = "5409"
    const val LUNG_SQUAMOUS_CELL_CARCINOMA_DOID = "3907"
    const val LYMPH_NODE_CANCER_DOID = "10619"
    const val LYMPHOMA_DOID = "0060058"
    const val LYMPHOMA_LARGE_B_CELL_DOID = "0081452"
    const val LYMPHOMA_ANAPLASTIC_LARGE_CELL_DOID = "0050744"
    const val LYMPHOMA_ANAPLASTIC_LARGE_CELL_BREAST_IMPLANT_ASSOCIATED_DOID = "0070333"
    const val MAIN_BRONCHUS_CANCER_DOID = "3924"
    const val MAST_CELL_NEOPLASM_DOID = "3664"
    const val MEDULLOBLASTOMA_LARGE_CELL_DOID = "3857"
    const val MUCINOUS_ADENOCARCINOMA_DOID = "3030"
    const val MUCINOUS_OVARIAN_CYSTADENOMA_DOID = "3267"
    const val MULTIPLE_MYELOMA_DOID = "9538"
    const val MYELOID_SARCOMA_DOID = "8683"
    const val NEUROENDOCRINE_CARCINOMA_DOID = "1800"
    const val NEUROENDOCRINE_TUMOR_DOID = "169"
    const val ORGAN_SYSTEM_CANCER_DOID = "0050686"
    const val OVARIAN_CANCER_DOID = "2394"
    const val OVARIAN_CARCINOMA_DOID = "4001"
    const val OVARIAN_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID = "4555"
    const val OVARIAN_MUCINOUS_ADENOCARCINOMA_DOID = "3606"
    const val OVARIAN_MUCINOUS_ADENOFIBROMA_DOID = "6469"
    const val OVARIAN_MUCINOUS_CYSTADENOCARCINOMA_DOID = "3604"
    const val OVARIAN_MUCINOUS_CYSTADENOFIBROMA_DOID = "7013"
    const val OVARIAN_MUCINOUS_MALIGNANT_ADENOFIBROMA_DOID = "6278"
    const val OVARIAN_MUCINOUS_NEOPLASM_DOID = "6067"
    const val OVARIAN_SEROMUCINOUS_CARCINOMA_DOID = "6898"
    const val OVARIAN_SMALL_CELL_CARCINOMA_DOID = "6179"
    const val PROGESTERONE_NEGATIVE_BREAST_CANCER_DOID = "0060078"
    const val PROGESTERONE_POSITIVE_BREAST_CANCER_DOID = "0060077"
    const val PROSTATE_CANCER_DOID = "10283"
    const val PROSTATE_SMALL_CELL_CARCINOMA_DOID = "7141"
    const val PULMONARY_TYPE_OVARIAN_SMALL_CELL_CARCINOMA_DOID = "7650"
    const val PULMONARY_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID = "6658"
    const val RECTUM_NEUROENDOCRINE_NEOPLASM_DOID = "5777"
    const val REFRACTORY_HEMATOLOGIC_CANCER_DOID = "712"
    const val SARCOMA_DOID = "1115"
    const val SMALL_CELL_CARCINOMA_DOID = "0050685"
    const val SMALL_CELL_CARCINOMA_OF_THE_OVARY_OF_HYPERCALCEMIC_TYPE_DOID = "7651"
    const val SMALL_CELL_OSTEOGENIC_SARCOMA_DOID = "3377"
    const val SMALL_CELL_SARCOMA_DOID = "3098"
    const val STOMACH_CANCER_DOID = "10534"
    const val THYMUS_SMALL_CELL_CARCINOMA_DOID = "7142"
    const val THYMUS_LARGE_CELL_CARCINOMA_DOID = "4553"
    const val TRACHEAL_CANCER_DOID = "11920"
    const val TRIPLE_NEGATIVE_BREAST_CANCER_DOID = "0060081"
    const val URETER_SMALL_CELL_CARCINOMA_DOID = "6886"
    const val URINARY_BLADDER_SMALL_CELL_NEUROENDOCRINE_CARCINOMA_DOID = "7132"

    val LUNG_NON_SQUAMOUS_NSCLC_DOIDS =
        setOf(LUNG_ADENOCARCINOMA_DOID, LUNG_LARGE_CELL_CARCINOMA_DOID, LUNG_NON_SQUAMOUS_NON_SMALL_CARCINOMA_DOID)

    val NEUROENDOCRINE_DOIDS = setOf(NEUROENDOCRINE_CARCINOMA_DOID, NEUROENDOCRINE_TUMOR_DOID)

    val NON_SOLID_CANCER_DOIDS = setOf(LEUKEMIA_DOID, REFRACTORY_HEMATOLOGIC_CANCER_DOID, BONE_MARROW_CANCER_DOID)

    val SMALL_CELL_LUNG_CANCER_DOIDS = setOf(
        LUNG_COMBINED_TYPE_SMALL_CELL_ADENOCARCINOMA_DOID,
        LUNG_COMBINED_TYPE_SMALL_CELL_CARCINOMA_DOID,
        LUNG_MIXED_SMALL_CELL_AND_SQUAMOUS_CELL_CARCINOMA_DOID,
        LUNG_OCCULT_SMALL_CELL_CARCINOMA_DOID,
        LUNG_SMALL_CELL_CARCINOMA_DOID,
    )

    val LARGE_CELL_CANCER_DOIDS = setOf(
        ACANTHOMA_LARGE_CELL_DOID,
        BREAST_LARGE_CELL_KERATINIZING_VARIANT_SQUAMOUS_CELL_CARCINOMA_DOID,
        BREAST_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID,
        CERVIX_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID,
        LARGE_CELL_CARCINOMA,
        LARGE_CELL_CARCINOMA_WITH_RHABDOID_PHENOTYPE_DOID,
        LEUKEMIA_T_CELL_LARGE_GRANULAR_LYMPHOCYTE_DOID,
        LUNG_COMBINED_TYPE_LARGE_CELL_CARCINOMA_DOID,
        LUNG_LARGE_CELL_CARCINOMA_DOID,
        LUNG_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID,
        LUNG_MIXED_SMALL_CELL_AND_SQUAMOUS_CELL_CARCINOMA_DOID,
        LUNG_OCCULT_LARGE_CELL_CARCINOMA_DOID,
        LYMPHOMA_ANAPLASTIC_LARGE_CELL_BREAST_IMPLANT_ASSOCIATED_DOID,
        LYMPHOMA_ANAPLASTIC_LARGE_CELL_DOID,
        LYMPHOMA_LARGE_B_CELL_DOID,
        MEDULLOBLASTOMA_LARGE_CELL_DOID,
        OVARIAN_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID,
        PULMONARY_LARGE_CELL_NEUROENDOCRINE_CARCINOMA_DOID,
        THYMUS_LARGE_CELL_CARCINOMA_DOID,
    )

    val SMALL_CELL_CANCER_DOIDS = setOf(
        AMPULLA_OF_VATER_SMALL_CELL_CARCINOMA_DOID,
        BARTHOLINS_GLAND_SMALL_CELL_CARCINOMA_DOID,
        BLADDER_SMALL_CELL_CARCINOMA_DOID,
        CERVIX_SMALL_CELL_CARCINOMA_DOID,
        COLON_SMALL_CELL_CARCINOMA_DOID,
        ENDOMETRIAL_SMALL_CELL_CARCINOMA_DOID,
        ESOPHAGUS_SMALL_CELL_CARCINOMA_DOID,
        EXTRAHEPATIC_BILE_DUCT_SMALL_CELL_ADENOCARCINOMA_DOID,
        GALLBLADDER_SMALL_CELL_CARCINOMA_DOID,
        GASTRIC_SMALL_CELL_CARCINOMA_DOID,
        LARYNGEAL_SMALL_CELL_CARCINOMA_DOID,
        LUNG_COMBINED_TYPE_SMALL_CELL_ADENOCARCINOMA_DOID,
        LUNG_COMBINED_TYPE_SMALL_CELL_CARCINOMA_DOID,
        LUNG_MIXED_SMALL_CELL_AND_SQUAMOUS_CELL_CARCINOMA_DOID,
        LUNG_OCCULT_SMALL_CELL_CARCINOMA_DOID,
        LUNG_SMALL_CELL_CARCINOMA_DOID,
        OVARIAN_SMALL_CELL_CARCINOMA_DOID,
        PROSTATE_SMALL_CELL_CARCINOMA_DOID,
        PULMONARY_TYPE_OVARIAN_SMALL_CELL_CARCINOMA_DOID,
        SMALL_CELL_CARCINOMA_DOID,
        SMALL_CELL_CARCINOMA_OF_THE_OVARY_OF_HYPERCALCEMIC_TYPE_DOID,
        SMALL_CELL_OSTEOGENIC_SARCOMA_DOID,
        SMALL_CELL_SARCOMA_DOID,
        THYMUS_SMALL_CELL_CARCINOMA_DOID,
        URETER_SMALL_CELL_CARCINOMA_DOID,
        URINARY_BLADDER_SMALL_CELL_NEUROENDOCRINE_CARCINOMA_DOID,
    )
}