package com.hartwig.actin.datamodel.clinical.treatment

import kotlin.text.lowercase
import kotlin.text.replace
import kotlin.to

enum class DrugType(override val category: TreatmentCategory, private val display: String? = null) : TreatmentType {
    ABL_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ABL inhibitor"),
    ABL1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ABL1 inhibitor"),
    ABL_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ABL TKI"),
    ABL1_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ABL1 TKI"),
    ADENOSINE_TARGETING(TreatmentCategory.IMMUNOTHERAPY),
    ADRENOLYTIC_AGENT(TreatmentCategory.CHEMOTHERAPY),
    ALK_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ALK inhibitor"),
    ALK_INHIBITOR_GEN_1(TreatmentCategory.TARGETED_THERAPY, "ALK inhibitor (1st gen)"),
    ALK_INHIBITOR_GEN_2(TreatmentCategory.TARGETED_THERAPY, "ALK inhibitor (2nd gen)"),
    ALK_INHIBITOR_GEN_3(TreatmentCategory.TARGETED_THERAPY, "ALK inhibitor (3rd gen)"),
    ALK_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ALK TKI"),
    ALKYLATING_AGENT(TreatmentCategory.CHEMOTHERAPY),
    ANGIOGENESIS_INHIBITOR(TreatmentCategory.TARGETED_THERAPY),
    ANTHRACYCLINE(TreatmentCategory.CHEMOTHERAPY),
    ANTI_ANDROGEN(TreatmentCategory.HORMONE_THERAPY, "anti-androgen"),
    ANTI_B7H3(TreatmentCategory.IMMUNOTHERAPY, "anti-B7H3"),
    ANTI_B7H4(TreatmentCategory.IMMUNOTHERAPY, "anti-B7H4"),
    ANTI_B7H3_ANTIBODY_DRUG_CONJUGATE(TreatmentCategory.TARGETED_THERAPY, "anti-B7H3 antibody-drug conjugate"),
    ANTI_CCR4(TreatmentCategory.IMMUNOTHERAPY, "anti-CCR4"),
    ANTI_CCR8(TreatmentCategory.IMMUNOTHERAPY, "anti-CCR8"),
    ANTI_CD137(TreatmentCategory.IMMUNOTHERAPY, "anti-CD137"),
    ANTI_CD16A(TreatmentCategory.IMMUNOTHERAPY, "anti-CD16A"),
    ANTI_CD25(TreatmentCategory.IMMUNOTHERAPY, "anti-CD25"),
    ANTI_CD276_ANTIBODY_DRUG_CONJUGATE(TreatmentCategory.TARGETED_THERAPY, "anti-CD276 antibody-drug conjugate"),
    ANTI_CD3(TreatmentCategory.TARGETED_THERAPY, "anti-CD3"),
    ANTI_CD40_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "anti-CD40 antibody"),
    ANTI_CD9_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "anti-CD9 antibody"),
    ANTI_CEACAM5(TreatmentCategory.TARGETED_THERAPY, "anti-CEACAM5"),
    ANTI_CLDN6_CAR_T(TreatmentCategory.IMMUNOTHERAPY, "anti-CLDN6 CAR-T"),
    ANTI_CLDN18_2(TreatmentCategory.IMMUNOTHERAPY, "anti-CLDN18.2"),
    ANTI_CTLA4(TreatmentCategory.IMMUNOTHERAPY, "anti-CTLA4"),
    ANTI_DLL3(TreatmentCategory.TARGETED_THERAPY, "anti-DLL3"),
    ANTI_ESTROGEN(TreatmentCategory.HORMONE_THERAPY, "anti-estrogen"),
    ANTI_KLK2(TreatmentCategory.TARGETED_THERAPY, "anti-KLK2"),
    ANTI_LAG_3(TreatmentCategory.IMMUNOTHERAPY, "anti-LAG-3"),
    ANTI_MAGE_4_8_TCR_THERAPY(TreatmentCategory.IMMUNOTHERAPY, "anti-MAGE-4/8 TCR-based therapy"),
    ANTI_NKG2D(TreatmentCategory.IMMUNOTHERAPY, "anti-NKG2D"),
    ANTI_NY_ESO_1(TreatmentCategory.IMMUNOTHERAPY, "anti-NY-ESO-1"),
    ANTI_OX40(TreatmentCategory.IMMUNOTHERAPY, "anti-OX40"),
    ANTI_PD_1_LAG_3(TreatmentCategory.IMMUNOTHERAPY, "anti-PD-1/LAG-3"),
    ANTI_PD_1_TIM_3(TreatmentCategory.IMMUNOTHERAPY, "anti-PD-1/TIM-3"),
    ANTI_PD_1(TreatmentCategory.IMMUNOTHERAPY, "anti-PD-1"),
    ANTI_PD_L1(TreatmentCategory.IMMUNOTHERAPY, "anti-PD-L1"),
    ANTI_PD_L2(TreatmentCategory.IMMUNOTHERAPY, "anti-PD-L2"),
    ANTI_PRAME_TCR_THERAPY(TreatmentCategory.IMMUNOTHERAPY, "anti-PRAME TCR-based therapy"),
    ANTI_TIGIT(TreatmentCategory.IMMUNOTHERAPY, "anti-TIGIT"),
    ANTI_TIM_3(TreatmentCategory.IMMUNOTHERAPY, "anti-TIM-3"),
    ANTI_TISSUE_FACTOR(TreatmentCategory.TARGETED_THERAPY, "anti tissue-factor (TF)"),
    ANTIBIOTIC(TreatmentCategory.SUPPORTIVE_TREATMENT, "antibiotic"),
    ANTIBODY_DRUG_CONJUGATE_IMMUNOTHERAPY(TreatmentCategory.IMMUNOTHERAPY, "antibody-drug conjugate"),
    ANTIBODY_DRUG_CONJUGATE_TARGETED_THERAPY(TreatmentCategory.TARGETED_THERAPY, "antibody-drug conjugate"),
    ANTIMETABOLITE(TreatmentCategory.CHEMOTHERAPY),
    ANTIMICROTUBULE_AGENT(TreatmentCategory.CHEMOTHERAPY),
    AROMATASE_INHIBITOR(TreatmentCategory.HORMONE_THERAPY),
    AUTOLOGOUS_CELL_IMMUNOTHERAPY(TreatmentCategory.IMMUNOTHERAPY),
    AXL_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "AXL inhibitor"),
    AXL_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "AXL TKI"),
    BCR_ABL_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "BCR-ABL inhibitor"),
    BCR_ABL_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "BCR-ABL TKI"),
    BISPHOSPHONATE(TreatmentCategory.SUPPORTIVE_TREATMENT),
    BRAF_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "BRAF inhibitor"),
    BRAF_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "BRAF TKI"),
    CALCIUM_REGULATORY_MEDICATION(TreatmentCategory.SUPPORTIVE_TREATMENT),
    CD73_ANTIBODY(TreatmentCategory.IMMUNOTHERAPY, "CD73 antibody"),
    CDK_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CDK inhibitor"),
    CDK2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CDK2 inhibitor"),
    CDK4_6_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CDK4/6 inhibitor"),
    CDK4_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CDK4 inhibitor"),
    CDK6_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CDK6 inhibitor"),
    CELL_BASED_IMMUNOTHERAPY(TreatmentCategory.IMMUNOTHERAPY),
    CORTICOSTEROID(TreatmentCategory.SUPPORTIVE_TREATMENT),
    CRAF_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CRAF inhibitor"),
    CRAF_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CRAF TKI"),
    CSF1R_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CSF1R inhibitor"),
    CSF1R_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "CSF1R TKI"),
    CTLA4_INHIBITOR(TreatmentCategory.IMMUNOTHERAPY, "CTLA4 inhibitor"),
    CYTOKINE(TreatmentCategory.IMMUNOTHERAPY),
    DDR1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "DDR1 inhibitor"),
    DDR1_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "DDR1 TKI"),
    DDR2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "DDR2 inhibitor"),
    DDR2_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "DDR2 TKI"),
    DNMT_INHIBITOR(TreatmentCategory.CHEMOTHERAPY, "DNMT inhibitor"),
    EGFR_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "EGFR antibody"),
    EGFR_C797X_TKI(TreatmentCategory.TARGETED_THERAPY, "EGFR C797X targeting TKI"),
    EGFR_EXON_20_INS_BISPECIFIC_ANTIBODIES(TreatmentCategory.TARGETED_THERAPY, "EGFR ex20ins bispecific antibody"),
    EGFR_EXON_20_INS_TARGETED_THERAPY(TreatmentCategory.TARGETED_THERAPY, "EGFR ex20ins targeting therapy"),
    EGFR_EXON_20_INS_TKI(TreatmentCategory.TARGETED_THERAPY, "EGFR ex20ins targeting TKI"),
    EGFR_INHIBITOR_GEN_1(TreatmentCategory.TARGETED_THERAPY, "EGFR inhibitor (1st gen)"),
    EGFR_INHIBITOR_GEN_2(TreatmentCategory.TARGETED_THERAPY, "EGFR inhibitor (2nd gen)"),
    EGFR_INHIBITOR_GEN_3(TreatmentCategory.TARGETED_THERAPY, "EGFR inhibitor (3rd gen)"),
    EGFR_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "EGFR inhibitor"),
    EGFR_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "EGFR TKI"),
    ERBB2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ERBB2 inhibitor"),
    FGFR_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR inhibitor"),
    FGFR_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR TKI"),
    FGFR1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR1 inhibitor"),
    FGFR1_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR1 TKI"),
    FGFR2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR2 inhibitor"),
    FGFR2_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR2 TKI"),
    FGFR3_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR3 inhibitor"),
    FGFR3_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR3 TKI"),
    FGFR4_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR4 inhibitor"),
    FGFR4_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FGFR4 TKI"),
    PAN_FGFR_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "pan-FGFR inhibitor"),
    PAN_FGFR_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "pan-FGFR TKI"),
    FLT3_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FLT3 inhibitor"),
    FLT3_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FLT3 TKI"),
    FLT3L_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "FLT3L inhibitor"),
    FLUOROPYRIMIDINE(TreatmentCategory.CHEMOTHERAPY),
    FOLR1_TARGETING_THERAPY(TreatmentCategory.TARGETED_THERAPY, "FOLR1 targeting therapy"),
    GAMMA_SECRETASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY),
    GONADOTROPIN_AGONIST(TreatmentCategory.HORMONE_THERAPY),
    GONADOTROPIN_ANTAGONIST(TreatmentCategory.HORMONE_THERAPY),
    HEDGEHOG_PATHWAY_INHIBITOR(TreatmentCategory.TARGETED_THERAPY),
    HER_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "HER inhibitor"),
    HER_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "HER TKI"),
    HER2_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "HER2 antibody"),
    HER2_CAR_T(TreatmentCategory.IMMUNOTHERAPY, "HER2 CAR-T"),
    HER2_EXON_20_INS_TKI(TreatmentCategory.TARGETED_THERAPY, "HER2 ex20ins targeting TKI"),
    HER2_IMMUNOTHERAPY(TreatmentCategory.IMMUNOTHERAPY, "HER2 antibody"),
    HER2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "HER2 inhibitor"),
    HER2_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "HER2 TKI"),
    HER3_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "HER3 antibody"),
    HIF_2A_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "HIF-2α inhibitor"),
    HORMONE_ANTINEOPLASTIC(TreatmentCategory.HORMONE_THERAPY),
    HPV_VACCINE(TreatmentCategory.IMMUNOTHERAPY, "HPV vaccine"),
    HPV16_VACCINE(TreatmentCategory.IMMUNOTHERAPY, "HPV-16 vaccine"),
    IDH_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "IDH inhibitor"),
    IDO1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "IDO1 inhibitor"),
    IGF_1R_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "IGF-1R inhibitor"),
    IGF_1R_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "IGF-1R TKI"),
    IL_15_CYTOKINE(TreatmentCategory.IMMUNOTHERAPY, "IL-15 cytokine"),
    IL_2_CYTOKINE(TreatmentCategory.IMMUNOTHERAPY, "IL-2 cytokine"),
    IMMTAC(TreatmentCategory.TARGETED_THERAPY, "ImmTAC"),
    IMMUNE_AGONIST(TreatmentCategory.IMMUNOTHERAPY),
    IMMUNE_CHECKPOINT_INHIBITOR(TreatmentCategory.IMMUNOTHERAPY),
    IMMUNOMODULATOR(TreatmentCategory.IMMUNOTHERAPY),
    JAK2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "JAK2 inhibitor"),
    JAK2_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "JAK2 TKI"),
    KIT_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "KIT inhibitor"),
    KIT_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "KIT TKI"),
    KRAS_G12C_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "KRAS G12C inhibitor"),
    KRAS_OFF_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "KRAS-off inhibitor"),
    MAT2A_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MAT2A inhibitor"),
    MEK_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MEK inhibitor"),
    MEK1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MEK1 inhibitor"),
    MEK2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MEK2 inhibitor"),
    MET_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "MET antibody"),
    MET_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MET inhibitor"),
    MET_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MET TKI"),
    MONOCLONAL_ANTIBODY_IMMUNOTHERAPY(TreatmentCategory.IMMUNOTHERAPY, "monoclonal antibody - immunotherapies"),
    MONOCLONAL_ANTIBODY_MMAE_CONJUGATE(TreatmentCategory.TARGETED_THERAPY, "monoclonal antibody - MMAE conjugate"),
    MONOCLONAL_ANTIBODY_SUPPORTIVE_TREATMENT(TreatmentCategory.SUPPORTIVE_TREATMENT, "monoclonal antibody - supportive treatments"),
    MONOCLONAL_ANTIBODY_TARGETED_THERAPY(TreatmentCategory.TARGETED_THERAPY, "monoclonal antibody - targeted therapies"),
    MTORC1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MTORC1 inhibitor"),
    MUC16_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "MUC16 inhibitor"),
    NECTIN_4_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "Nectin-4 antibody"),
    NK_CELL_BASED_THERAPY(TreatmentCategory.IMMUNOTHERAPY, "NK cell-based therapy"),
    NITROSOUREAS(TreatmentCategory.CHEMOTHERAPY),
    NONSTEROIDAL_ANTI_ANDROGEN(TreatmentCategory.HORMONE_THERAPY),
    NOTCH_INHIBITOR(TreatmentCategory.TARGETED_THERAPY),
    NOVEL_HORMONE_THERAPY_FOR_PROSTATE(TreatmentCategory.HORMONE_THERAPY),
    PARP_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PARP inhibitor"),
    PD_1_PD_L1_ANTIBODY(TreatmentCategory.IMMUNOTHERAPY, "PD-1/PD-L1 antibody"),
    PDGFR_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PDGFR inhibitor"),
    PDGFR_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PDGFR TKI"),
    PDGFRA_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PDGFRA inhibitor"),
    PDGFRA_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PDGFRA TKI"),
    PDGFRB_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PDGFRB inhibitor"),
    PDGFRB_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PDGFRB TKI"),
    PIK3CA_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PIK3CA inhibitor"),
    PLATINUM_COMPOUND(TreatmentCategory.CHEMOTHERAPY),
    PRMT5_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "PRMT5 inhibitor"),
    PROGESTIN(TreatmentCategory.HORMONE_THERAPY),
    PYRIMIDINE_ANTAGONIST(TreatmentCategory.CHEMOTHERAPY),
    RAF_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "RAF inhibitor"),
    RAF_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "RAF TKI"),
    RAS_ON_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "RAS-on inhibitor"),
    RANKL_ANTIBODY(TreatmentCategory.SUPPORTIVE_TREATMENT, "RANKL antibody"),
    RET_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "RET inhibitor"),
    RET_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "RET TKI"),
    RON_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "RON inhibitor"),
    RON_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "RON TKI"),
    ROS1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ROS1 inhibitor"),
    ROS1_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "ROS1 TKI"),
    SHP2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "SHP2 inhibitor"),
    SOMATOSTATIN_ANALOGUE(TreatmentCategory.SUPPORTIVE_TREATMENT),
    SMO_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "SMO inhibitor"),
    SOS1_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "SOS1 inhibitor"),
    SRC_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "SRC inhibitor"),
    SRC_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "SRC TKI"),
    STEROID(TreatmentCategory.SUPPORTIVE_TREATMENT),
    TAXANE(TreatmentCategory.CHEMOTHERAPY),
    THYMIDINE_PHOSPHORYLASE_INHIBITOR(TreatmentCategory.CHEMOTHERAPY),
    TDO_INHIBITOR(TreatmentCategory.IMMUNOTHERAPY, "TDO inhibitor"),
    TIL_IMMUNOTHERAPY(TreatmentCategory.IMMUNOTHERAPY, "TIL-based immunotherapy"),
    TLR_AGONIST(TreatmentCategory.IMMUNOTHERAPY, "TLR agonist"),
    TOPO1_INHIBITOR(TreatmentCategory.CHEMOTHERAPY, "TOPO1 inhibitor"),
    TOPO2_INHIBITOR(TreatmentCategory.CHEMOTHERAPY, "TOPO2 inhibitor"),
    TRK_RECEPTOR_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "TRK receptor inhibitor"),
    TRK_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "TRK TKI"),
    TROP2_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "TROP2 antibody"),
    TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY),
    TYROSINE_KINASE_INHIBITOR_GEN_1(TreatmentCategory.TARGETED_THERAPY),
    TYROSINE_KINASE_INHIBITOR_GEN_2(TreatmentCategory.TARGETED_THERAPY),
    TYROSINE_KINASE_INHIBITOR_GEN_3(TreatmentCategory.TARGETED_THERAPY),
    VACCINE(TreatmentCategory.IMMUNOTHERAPY),
    VEGF_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "VEGF antibody"),
    VEGF_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "VEGF TKI"),
    VEGFR_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "VEGFR inhibitor"),
    VEGFR_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "VEGFR TKI"),
    VEGFR2_ANTIBODY(TreatmentCategory.TARGETED_THERAPY, "VEGFR2 antibody"),
    VEGFR2_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "VEGFR2 inhibitor"),
    VEGFR2_TYROSINE_KINASE_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "VEGFR2 TKI"),
    WRN_INHIBITOR(TreatmentCategory.TARGETED_THERAPY, "WRN inhibitor");

    override fun display(): String {
        return display ?: Enum.toString().replace("_", " ").lowercase()
    }

    companion object {
        val NSCLC_SOC_TARGETED_THERAPY_DRUG_TYPES = mapOf(
            "ALK" to setOf(
                ALK_INHIBITOR,
                ALK_TYROSINE_KINASE_INHIBITOR,
                ALK_INHIBITOR_GEN_1,
                ALK_INHIBITOR_GEN_2,
                ALK_INHIBITOR_GEN_3
            ),
            "BRAF" to setOf(
                BRAF_INHIBITOR,
                BRAF_TYROSINE_KINASE_INHIBITOR
            ),
            "EGFR" to setOf(
                EGFR_INHIBITOR,
                EGFR_EXON_20_INS_TARGETED_THERAPY,
                EGFR_C797X_TKI,
                EGFR_INHIBITOR_GEN_1,
                EGFR_INHIBITOR_GEN_2,
                EGFR_INHIBITOR_GEN_3,
                EGFR_EXON_20_INS_TARGETED_THERAPY,
                EGFR_TYROSINE_KINASE_INHIBITOR
            ),
            "ERBB2" to setOf(
                HER2_ANTIBODY,
                HER2_INHIBITOR,
                HER2_TYROSINE_KINASE_INHIBITOR,
                HER2_EXON_20_INS_TKI,
            ),
            "KRAS" to setOf(
                KRAS_G12C_INHIBITOR,
            ),
            "MET" to setOf(
                MET_INHIBITOR,
                MET_TYROSINE_KINASE_INHIBITOR
            ),
            "NTRK1" to setOf(
                TRK_RECEPTOR_INHIBITOR,
                TRK_TYROSINE_KINASE_INHIBITOR
            ),
            "NTRK2" to setOf(
                TRK_RECEPTOR_INHIBITOR,
                TRK_TYROSINE_KINASE_INHIBITOR
            ),
            "NTRK3" to setOf(
                TRK_RECEPTOR_INHIBITOR,
                TRK_TYROSINE_KINASE_INHIBITOR
            ),
            "RET" to setOf(
                RET_INHIBITOR,
                RET_TYROSINE_KINASE_INHIBITOR
            ),
            "ROS1" to setOf(
                ROS1_INHIBITOR,
                ROS1_TYROSINE_KINASE_INHIBITOR
            )
        )

        val RAS_MEK_MAPK_DIRECTLY_TARGETING_DRUG_SET = setOf(
            KRAS_G12C_INHIBITOR,
            BRAF_INHIBITOR,
            BRAF_TYROSINE_KINASE_INHIBITOR,
            MEK_INHIBITOR,
            MEK1_INHIBITOR,
            MEK2_INHIBITOR
        )

        val RAS_MEK_MAPK_INDIRECTLY_TARGETING_DRUG_SET = setOf(
            ERBB2_INHIBITOR,
            HER2_INHIBITOR,
            HER2_ANTIBODY,
            HER3_ANTIBODY,
            HER_INHIBITOR,
            HER_TYROSINE_KINASE_INHIBITOR,
            PDGFR_INHIBITOR,
            PDGFRA_INHIBITOR,
            PDGFRB_INHIBITOR,
            PDGFR_TYROSINE_KINASE_INHIBITOR,
            PDGFRA_TYROSINE_KINASE_INHIBITOR,
            PDGFRB_TYROSINE_KINASE_INHIBITOR,
            FGFR_INHIBITOR,
            FGFR1_INHIBITOR,
            FGFR2_INHIBITOR,
            FGFR3_INHIBITOR,
            FGFR4_INHIBITOR,
            PAN_FGFR_INHIBITOR,
            FGFR_TYROSINE_KINASE_INHIBITOR,
            FGFR1_TYROSINE_KINASE_INHIBITOR,
            FGFR2_TYROSINE_KINASE_INHIBITOR,
            FGFR3_TYROSINE_KINASE_INHIBITOR,
            FGFR4_TYROSINE_KINASE_INHIBITOR,
            PAN_FGFR_TYROSINE_KINASE_INHIBITOR
        )
    }
}